apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-spring-project
  namespace: hello-world
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-spring-project
  template:
    metadata:
      labels:
        app: my-spring-project
    spec:
      containers:
      - name: my-spring-project
        image: zuneha/my-spring-project:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-spring-project
  namespace: hello-world
spec:
  selector:
    app: my-spring-project
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
