

---
apiVersion: v1
kind: Config
current-context: shoot--kyma--e65d9b2
clusters:
- name: shoot--kyma--e65d9b2
  cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUM1akNDQWM2Z0F3SUJBZ0lRTmJEVUFNYTc5QUQ3QWpuM09BeitLVEFOQmdrcWhraUc5dzBCQVFzRkFEQU4KTVFzd0NRWURWUVFERXdKallUQWVGdzB5TXpBME1qVXhPVFEzTVRCYUZ3MHpNekEwTWpVeE9UUTNNVEJhTUEweApDekFKQmdOVkJBTVRBbU5oTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUE5Sk00CmhHYmc1ek9ReHYranhreFJPcEkvRGR1UTVVMmZUZVZxdGxkTDB4NC9ORnQwckNJRmJ3MFBHclRhaHVOUkZjRHEKZUpzYmJMWi9HcXBIMzBTZlNQL1dJQUpXRS9pQzRjb2dxMm96Zm9NUTN2cnRiWFdZbzR4VjBRbUV5ck9mWGxrVAptdFZuazBVRllVT0ZHVk1mOU1US3Y3Q0c3ZW1JZlBEUWpra3lQd0VocGtjRGloNUVNbmQ4cGQ3OHpaQWx2SzBICkZ6bTVGaElQS0NndlVqL1pINXo3bXJlalM2U0xld3V5Nlk5S1gxeldZUEdTaVcyb20wMkk5SkF4eTF3K2NPNzAKWWpqbHo3cHBLYmc2VVNsSEllVEp3WDNSNkdhcHpIZDR5S2NLT21xQWxocHNKdWxJdklXUnU0Y2hnQnF6SndXVwpyRkhkTFBHNmtENkI0QU9NWHdJREFRQUJvMEl3UURBT0JnTlZIUThCQWY4RUJBTUNBYVl3RHdZRFZSMFRBUUgvCkJBVXdBd0VCL3pBZEJnTlZIUTRFRmdRVVpUZEMwN3ExL0FPM1Vxd2puNWtCV01Eb0lBMHdEUVlKS29aSWh2Y04KQVFFTEJRQURnZ0VCQUtFcVV3S2RqeW9NemRrN0J6MkF5MXE5UHNYNTIxdzNaY092d1p2d1FuTHZ0aGtMUE1pQQozVXJET1VuUVMvUDA5YUpTYVlnVytyRWJ1N2lOT3cwb3B5dnE5aS9nanBsZnNDTXBRb0Y3eURmWFZRVnhjZDZ2ClRuQ3ltV3dBWXFzblhBNExVc2N0TFA2K0RMdjlpREFiK2dqOWdEQUJFV01lQ0FHT1ZUdWlRcE1RQlkwTWFpT2cKSWtYaUtWdGJHUlpVSHpLWURkNmw1YkpyYWhUN0R2K09tVW5RRkpRWTJUWlJVMC84K2lHdnlDNVRlYVhLaHhNQQpmVHE2d28yUWxHVzFwTE84WVZuRVJXdlQ1NGlQbmx0UHhZNWpNMkZkeHR5NTZLS3A1aGVVWEFaekg5TVhTZUlMCk9ZL2U1Ky8ySms0QmZNZ2pnd2IwK1hkbTdqd2hXVW9MWm5nPQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    server: https://api.e65d9b2.kyma.ondemand.com
contexts:
- name: shoot--kyma--e65d9b2
  context:
    cluster: shoot--kyma--e65d9b2
    user: shoot--kyma--e65d9b2
users:
- name: shoot--kyma--e65d9b2
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--oidc-issuer-url=https://e876ebd7trial.authentication.us10.hana.ondemand.com/oauth/token"
      - "--oidc-client-id=sb-c7bae9e3-6fe8-4d2f-b233-1fbebdb0090b!b149330|service-manager!b1476"
      - "--oidc-client-secret=ea020775-883d-4b8b-8a4e-57c805bca8c4$ps2XtVMojXI4ZZLkLvk1h1MbPNXQMN-Kvf3zKIYjXWw="
      - "--oidc-extra-scope=email"
      - "--oidc-extra-scope=openid"
      - "--grant-type=password"
      - "--username=zukhanam@deloitte.com"
      - "--password=Mdkaifyy@786"
      command: kubelogin
      installHint: |
        kubelogin plugin is required to proceed with authentication
        # Homebrew (macOS and Linux)
        brew install int128/kubelogin/kubelogin
        # Krew (macOS, Linux, Windows and ARM)
        kubectl krew install oidc-login
        # Chocolatey (Windows)
        choco install kubelogin








