apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-example
  namespace: ${NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-example
  template:
    metadata:
      labels:
        app: spring-example
    spec:
      containers:
      - name: spring-example
        image: ${DOCKER_IMAGE}
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: spring-example
  namespace: ${NAMESPACE}
spec:
  selector:
    app: spring-example
  ports
