name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Build and Push Docker image
      run: |
        docker login -u zuneha -p dckr_pat_sPW-GvVMQ_dIxSdh4WguqW4BgvI
        docker build -t zuneha/my-spring-project:latest .
        docker push zuneha/my-spring-project:latest
  deploy-to-kyma:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Deploy to Kyma
      uses: steebchen/kubectl@v1.1.1
      with:
        args: apply -f deployment.yaml --kubeconfig=kubeconfig.yaml
        kubeconfig: ${{ github.workspace }}/kubeconfig.yaml
