name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
    - name: Build and Push Docker image
      run: |
        docker login -u zuneha -p dckr_pat_sPW-GvVMQ_dIxSdh4WguqW4BgvI
        docker build -t zuneha/my-spring-project:latest .
        docker push zuneha/my-spring-project:latest
  deploy-to-kyma:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Kubectl
      uses: azure/setup-kubectl@v1
      with:
        version: 'latest'

    - name: Install kubelogin
      run: |
        cd "$(mktemp -d)" &&
        curl -fsSLO "https://storage.googleapis.com/krew/v0.4.1/krew.tar.gz" &&
        tar zxvf krew.tar.gz &&
        KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_amd64" &&
        "$KREW" install --manifest-url https://raw.githubusercontent.com/int128/kubelogin/master/deploy/krew.yaml --archive krew.tar.gz &&
        echo "export PATH="${PATH}:${HOME}/.krew/bin"" >> ~/.bashrc &&
        export PATH="${PATH}:${HOME}/.krew/bin" &&
        kubectl krew install oidc-login

    - name: Deploy to Kyma
      run: |
        kubectl apply -f deployment.yaml --kubeconfig=kubeconfig.yaml
