name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8

    - name: Build with Maven
      run: mvn clean package

    - name: Set up Docker
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh

    - name: Build and Push Docker image
      run: |
        echo "dckr_pat_sPW-GvVMQ_dIxSdh4WguqW4BgvI" | docker login -u zuneha --password-stdin
        docker build -t zuneha/my-spring-project:latest .
        docker push zuneha/my-spring-project:latest

  deploy-to-kyma:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up kubectl
      run: |
        VERSION=$(curl --silent https://storage.googleapis.com/kubernetes-release/release/stable.txt)
        curl https://storage.googleapis.com/kubernetes-release/release/$VERSION/bin/linux/amd64/kubectl \
          --location \
          --remote-name
        chmod +x ./kubectl
        sudo mv ./kubectl /usr/local/bin/

    - name: Deploy to Kyma
      run: |
        kubectl --kubeconfig=kubeconfig.yaml apply -f ./deployment.yaml
